// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcAb8G7fQggICQF9fPVuy1PuXzt_h8I34',
    appId: '1:197762015084:web:1c84e5fe293169c2225d49',
    messagingSenderId: '197762015084',
    projectId: 'obase-fca43',
    authDomain: 'obase-fca43.firebaseapp.com',
    storageBucket: 'obase-fca43.appspot.com',
    measurementId: 'G-937RTKEV59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8OstwiuDbWENBfvR4Yg9xaHi2V7Ovolk',
    appId: '1:197762015084:android:310f28ce36227539225d49',
    messagingSenderId: '197762015084',
    projectId: 'obase-fca43',
    storageBucket: 'obase-fca43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi6V_10LPr85i_2Q3x7oXIk9YcHfLDp3w',
    appId: '1:197762015084:ios:70c2ba4a7807bc5c225d49',
    messagingSenderId: '197762015084',
    projectId: 'obase-fca43',
    storageBucket: 'obase-fca43.appspot.com',
    iosClientId: '197762015084-slkqtc9nu99dt7qv7r4ej1iat91v3mh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.obaseBarcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi6V_10LPr85i_2Q3x7oXIk9YcHfLDp3w',
    appId: '1:197762015084:ios:3e535b667610ef17225d49',
    messagingSenderId: '197762015084',
    projectId: 'obase-fca43',
    storageBucket: 'obase-fca43.appspot.com',
    iosClientId: '197762015084-qfto0m9bff711tg2pgh9716n4opd2jie.apps.googleusercontent.com',
    iosBundleId: 'com.example.obaseBarcode.RunnerTests',
  );
}
